language: python
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
services:
  - redis-server
# command to run tests
script: nosetests --with-coverage --cover-package=uwmenu
after_success: coveralls
