#!/bin/sh
# Usage: script/bootstrap
# Ensures UWOPENDATA_APIKEY is set, all modules are in virtualenv and installed locally, and that Redis is running.

if [[ -z "$UWOPENDATA_APIKEY" ]] && ! grep UWOPENDATA_APIKEY= .env >/dev/null; then
  echo "Enter your key for the University of Waterloo Open Data API:"
  read UWOPENDATA_APIKEY
  echo "UWOPENDATA_APIKEY=$UWOPENDATA_APIKEY" >> .env
fi
[[ -f venv/bin/activate ]] || virtualenv venv
[[ -f venv/bin/activate ]] && source venv/bin/activate
pip --quiet install --requirement requirements.txt
if ! hash redis-cli 2>/dev/null; then
  brew install redis && launchctl load ~/Library/LaunchAgents/homebrew.mxcl.redis.plist
else
  redis-cli ping >/dev/null 2>&1 || >&2 echo "Redis is not currently started. Please reload and try again."
fi
